boss_attributes:
  BOSS_伤害压缩百分比: 0
  BOSS_减爆伤: 900
  BOSS_厄运诅咒(绿点): 0
  BOSS_气血: 10000000
  BOSS_混乱诅咒: 120
  BOSS_防御: 0
my_attributes:
  主输出_1%攻击比面板攻击: 100
  主输出_1%气血比面板气血: 2500
  主输出_1%真气比面板真气: 2500
  主输出_1%防御比面板防御: 100
  主输出_三代白虎_天罡正觉神: 2级
  主输出_减爆伤: 1000
  主输出_对怪增伤: 4.6
  主输出_心法_乘时而化: true
  主输出_心法_太极_乘时而化: true
  主输出_心法_幽录_银鳞玄冰: false
  主输出_心法_玄清_乘时而化: true
  主输出_心法_般若_银鳞玄冰: false
  主输出_心法_银鳞玄冰: false
  主输出_技能_地煞狂灵形: false
  主输出_技能_碧海系: true
  主输出_技能_锐金咒: false
  主输出_最大攻击: 150000
  主输出_最小攻击: 120000
  主输出_气血: 1500000
  主输出_爆伤: 1600.0
  主输出_玄烛品质_云蒸霞蔚: 曦日
  主输出_玄烛品质_毒祭无常业: 曦日
  主输出_玄烛品质_痴情咒: 曦日
  主输出_真气: 1500000
  主输出_职业: 4
  主输出_自身防御力: 15000
  主输出_赤乌品质_大业浮屠: 曦日
  主输出_赤乌品质_森罗削空斩: 曦日
  主输出_防御: 100000
roles_para:
  九黎: {}
  天华:
    天华_前世职业_凤求凰: 太昊
    天华_技能_秋声雅韵: true
    天华_技能_金蛇狂舞: true
    天华_技能_鸣泉雅韵: false
    天华_最大攻击: 150000
    天华_真气: 1800000
  天音:
    天音_技能_慈航法愿: true
    天音_最大攻击: 150000
    天音_玄烛品质_摩柯心经: 皓月
    天音_真气: 2000000
  昭冥:
    昭冥_技能_日月弘光: true
    昭冥_最大攻击: 0
    昭冥_最小攻击: 0
    昭冥_气血: 1000000
    昭冥_爆伤: 1500.0
    昭冥_真气: 1000000
    昭冥_防御: 0
  焚香:
    焚香_技能_祝融真典2: true
  画影:
    画影_技能_凌寒拂霜: true
    画影_真气: 800000
  百灵:
    百灵_技能_灵雨续春: false
  英招: {}
  青云:
    青云_技能_五气朝元: true
  青罗:
    青罗_技能_研彻晓光: true
    青罗_技能_缓分花陌2: true
  鬼王:
    鬼王_真气: 800000
skill_para:
  大业浮屠·赤乌_附加固定攻击值: 5000
  大业浮屠·赤乌_附加本体攻击百分比: 390
  大业浮屠·赤乌_附加气血上限百分比: 90
  大业浮屠·赤乌_附加爆伤: 50
  大业浮屠·赤乌_附加真气上限百分比: 45
  大业浮屠·赤乌_附加防御上限百分比: 0
  技能名称: 大业浮屠·赤乌
  技能名称索引: 0
var_gains_para:
  三味真炎火: 4级
  三碗不过岗: 20
  九华淀魂曲: 4级
  八级雷煌闪: 4级
  副本赠送属性: 空桑兽神
  墨雪特效霜情: 20000
  情愫项链技能佳期: 10
  星语拔山: 20
  法宝融合爆伤: 0
  经典家族技能等级: 15阶
  进阶家族技能等级: 0.0
  雪琪的祈愿: 50
  龙虎之力: 龙虎3
